BookingCalendar/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Web.Security;

using DHTMLX.Common;
using DHTMLX.Scheduler;
using DHTMLX.Scheduler.Authentication;
using DHTMLX.Scheduler.Controls;
using DHTMLX.Scheduler.Data;
using RoomBookingCalendar.Models;
using System.Web.Script.Serialization;

namespace RoomBookingCalendar.Controllers
{
    public class BookingController : Controller
    {
        protected void _ConfigureLightbox(DHXScheduler sched, MyEventsDataContext context)
        {
            var select = new LightboxSelect("room_id", "Room");
            select.AddOptions(context.Rooms);
            sched.Lightbox.AddDefaults();
            sched.Lightbox.Items.Insert(1, select); 
        }

        protected void _ConfigureViewsAndTemplates(DHXScheduler sched, MyEventsDataContext context)
        {
            sched.Views.Items.RemoveAt(2);//remove DayView
         
            var units = new UnitsView("rooms", "room_id");
         
            units.Label = "Phòng";
            units.AddOptions(context.Rooms);          
            sched.Views.Add(units);
            sched.Views.Add(new WeekAgendaView());

            
        }

        protected void _ConfigureScheduler(DHXScheduler sched, MyEventsDataContext context)
        {
            sched.SetEditMode(EditModes.OwnEventsOnly, EditModes.AuthenticatedOnly);
            sched.Extensions.Add(SchedulerExtensions.Extension.Collision);
            sched.Extensions.Add(SchedulerExtensions.Extension.Limit);
           
            

            sched.Config.first_hour = 7;
            sched.Config.last_hour = 20;
            sched.XY.scroll_width = 0;
            sched.Config.time_step = 30;
            sched.Config.multi_day = true;
            sched.Config.limit_time_select = true;

            sched.Config.cascade_event_display = true;


            sched.AfterInit = new List<string>() { "attachRules();" };

            sched.LoadData = true;
            sched.PreventCache();

            if (Request.IsAuthenticated)
            {
                sched.EnableDataprocessor = true;
            }  
        }
        protected void _HandleAuthorization(DHXScheduler sched, MyEventsDataContext context)
        {
            if (Request.IsAuthenticated)
            {
                var user = context.Users.SingleOrDefault(u => u.UserId == (Guid)Membership.GetUser().ProviderUserKey);
                sched.SetUserDetails(user, "UserId");
                sched.Authentication.EventUserIdKey = "user_id";

                sched.InitialValues.Add("textColor", user.color);
                sched.InitialValues.Add("room_id", context.Rooms.First().key);
            }

        }


        public ActionResult Index()
        {
            var sched = new DHXScheduler();
            var context = new MyEventsDataContext();
            sched.Skin = DHXScheduler.Skins.Glossy;
            sched.Codebase = Url.Content("~/Scripts/dhtmlxScheduler");
            sched.SaveAction = Url.Content("~/Booking/Save");
            sched.DataAction = Url.Content("~/Booking/Data");

            _ConfigureScheduler(sched, context);
            _ConfigureViewsAndTemplates(sched, context);
            _ConfigureLightbox(sched, context);
            _HandleAuthorization(sched, context);

                      
            var serializer = new JavaScriptSerializer();
            var rooms = serializer.Serialize(context.Rooms);
            var colors = serializer.Serialize(
                (from us in context.Users select new { id = us.UserId.ToString(), color = us.color })
                    .ToDictionary(t => t.id.ToLower(), t => t.color));


            return View(new CalendarModel() { Rooms = rooms, Colors = colors, Scheduler = sched });
        }
        public ActionResult Tutorial()
        {
            return View();
        }
        public ActionResult Data()
        {
            return (new SchedulerAjaxData((new MyEventsDataContext()).Events));         
        }

		public ActionResult Save(int? id, FormCollection actionValues)
		{
			var action = new DataAction(actionValues);
            var changedEvent = (Event)DHXEventsHelper.Bind(typeof(Event), actionValues);
            MyEventsDataContext data = new MyEventsDataContext();

            if (Request.IsAuthenticated && changedEvent.user_id == (Guid)Membership.GetUser().ProviderUserKey && changedEvent.start_date > DateTime.Now)
            {
               
                try
                {
                    switch (action.Type)
                    {
                        case DataActionTypes.Insert:
                            data.Events.InsertOnSubmit(changedEvent);
                            break;
                        case DataActionTypes.Delete:
                            changedEvent = data.Events.SingleOrDefault(ev => ev.id == action.SourceId);
                            data.Events.DeleteOnSubmit(changedEvent);
                            break;
                        default:// "update"                          
                            var eventToUpdate = data.Events.SingleOrDefault(ev => ev.id == action.SourceId);
                            DHXEventsHelper.Update(eventToUpdate, changedEvent, new List<string>() { "id" });
                            break;
                    }
                    data.SubmitChanges();
                    action.TargetId = changedEvent.id;
                }
                catch(Exception a)
                {
                    action.Type = DataActionTypes.Error;
                }
            }
            else
            {
                action.Type = DataActionTypes.Error;
            }

            return new AjaxSaveResponse(action);
		}

    }
}

BookingCalendar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Công đoàn HCMUTE</title>
    <link href="../../Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="shortcut icon" href="/Content/icon.png" />
    <style>
        .dhtmlx_message_area {
            background-color:red;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="pull-left" style=" padding-top: 4px;">
                <a href="/" class="btn btn-warning glyphicon glyphicon-home"></a>
            </div>
            <div class="pull-right" style="padding-top:2px;padding-bottom:2px;">
                @Html.Partial("_LogOnPartial")
            </div>
        </div>
    </div>
    <div class="container navbar navbar-fixed-bottom">
        <div class="row">
            <div class="pull-left" style="padding-top:10px;">
                <text style="color:white;">Copy right &copy; 2015 - Công đoàn trường Đại học Sư phạm Kỹ thuật Tp.HCM</text>
            </div>
            <div class="pull-right" style="padding-top:10px;">
                <script id="_wau9ff">
                    var _wau = _wau || []; _wau.push(["classic", "62cfc7tcfb1x", "9ff"]);
                    (function () {
                        var s = document.createElement("script"); s.async = true;
                        s.src = "http://widgets.amung.us/classic.js";
                        document.getElementsByTagName("head")[0].appendChild(s);
                    })();</script>
            </div>
        </div>
    </div>
    <div class="page">
        <div id="main">
            @RenderBody()

            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

BookingCalendar/Views/Shared/_LogOnPartial.cshtml
<span>
    @if (Request.IsAuthenticated)
    {
        <text>
            <b style="color:white">
                Xin chào, @Context.User.Identity.Name
            </b>
        </text>
        @Html.ActionLink("Đăng xuất", "LogOff", "Account", "", new { @class = "btn btn-danger" })
        @Html.ActionLink("Đổi mật khẩu", "ChangePassword", "Account", "", new { @class = "btn btn-warning" })
    }
    else
    {
        @Html.ActionLink("Đăng nhập", "LogOn", "Account", "", new { @class = "btn btn-success" })
    }
    @Html.ActionLink("Hướng dẫn", "Tutorial", "Booking", new { @class = "btn btn-info" })
</span>